name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_PROJECT_PATH: ./GitHubActionTestSolution/MyWebApplication
      TEST_PROJECT_PATH: ./GitHubActionTestSolution/NunitTestProject

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.304
    - name: Restore application dependencies
      run: dotnet restore ${{ env.APP_PROJECT_PATH }}
    - name: Build application
      run: dotnet build --no-restore ${{ env.APP_PROJECT_PATH }}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.TEST_PROJECT_PATH }}
